### All status related requests

## Variables

@baseUrl = http://localhost:8080/status
@token = Bearer {{getToken.response.body.$.token}}
@id = 7

# @name getToken
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "amy@gmail.com",
    "password": "1234"
}

###########################################################

### Endpoints

### create status ###
POST {{baseUrl}}
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "name": "para qa",
    "color": "verde"
}

### set a status on a task ###
POST {{baseUrl}}/set
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "task": 1,
    "status": 2
}

### list and search all status ###
GET {{baseUrl}}
Authorization: {{token}}
# param search searches by name

### update status by id ###
# id is mandatory
PUT {{baseUrl}}/{{id}}
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "name": "para apagar editado",
    "color": "rosa editada"
}

### delete status by id ###
# it is not possible to delete a status linked to a task
# id is mandatory
DELETE {{baseUrl}}/{{id}}
Authorization: {{token}}