### All task related requests

## Variables

@baseUrl = http://localhost:8080/task
@token = Bearer {{getToken.response.body.$.token}}
@id = 2

# @name getToken
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "amy@gmail.com",
    "password": "1234"
}

###################################################################

### Endpoints

### create task ###
POST {{baseUrl}}
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "name": "task com id nova 2",
    "description": "desc da task nova 2"
}

### get task by id ###
# id is mandatory
# id is a integer
GET {{baseUrl}}/{{id}}
Content-Type: application/json
Authorization: {{token}}


### list all tasks ###
GET {{baseUrl}}
Content-Type: application/json
Authorization: {{token}}

### update task ###
# id is mandatory
PUT {{baseUrl}}/{{id}}
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "name": "task com id 1 editada",
    "description": "desc da task com id 1"
}

### delete task by id ###
# id is mandatory
# admin role is required
DELETE {{baseUrl}}/{{id}}
Authorization: {{token}}

### add a responsible ###
POST {{baseUrl}}/responsible/add
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "taskId": 2,
    "responsibleId": 2
}

### remove a responsible ###
DELETE {{baseUrl}}/responsible/remove
Content-Type: application/json
Authorization: {{token}}

# all fields are mandatory
{
    "taskId": 1,
    "responsibleId": 2
}

